In [3]:
import pandas as pd

state = pd.read_csv('null.csv')
print(state)

            State Patients Saved Dead Active Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0                                      State   Patients      Saved       Dead
1                                Maharashtra    1919550    1809948      49255
2                                  Karnataka     916256     891095      12062
3                             Andhra Pradesh     881061     870342       7094
4                                 Tamil Nadu     814170     793154      12069
5                                     Kerala     740517     672196       2977
6                                      Delhi     622851     605685      10453
7                              Uttar Pradesh     581980     558303       8306
8                                West Bengal     547443     524071       9598
9                                     Odisha     328504     324068       1914
10                                 Rajasthan     305360     291533       2670
11                                 Telangana     284863     276753       1531
12                              Chhattisgarh     274324     257021       3275
13                                   Haryana     260907     253765       2874
14                                     Bihar     250995     244688       1383
15                                   Gujarat     241845     227228       4282
16                            Madhya Pradesh     238352     224692       3563
17                                     Assam     215939     211543       1037
18                                    Punjab     165405     155892       5299
19                         Jammu and Kashmir     120137     114986       1869
20                                 Jharkhand     114143     111530       1018
21                               Uttarakhand      89218      81154       1476
22                          Himachal Pradesh      54280      49040        901
23                                       Goa      50667      48992        731
24                                Puducherry      37947      36962        630
25                                   Tripura      33234      32672        382
26                                   Manipur      28029      26404        348
27                                Chandigarh      19486      18810        315
28                         Arunachal Pradesh      16687      16477         56
29                                 Meghalaya      13371      12985        138
30                                  Nagaland      11897      11438         78
31                                    Ladakh       9394       9050        126
32                                    Sikkim       5799       5063        125
33               Andaman and Nicobar Islands       4912       4789         62
34                                   Mizoram       4182       4049          8
35  Dadra and Nagar Haveli and Daman and Diu       3360       3318          2
36                          State Unassigned          0          0          0
37                               Lakshadweep        NaN        NaN        NaN

   Unnamed: 4
0      Active
1       59214
2       13080
3        3625
4        8947
5       65165
6        6713
7       15371
8       13774
9        2522
10      11157
11       6579
12      14028
13       4268
14       4923
15      10335
16      10097
17       3356
18       4214
19       3282
20       1595
21       5444
22       4292
23        944
24        355
25        157
26       1277
27        361
28        154
29        248
30        251
31        218
32        517
33         61
34        125
35         11
36          0
37        NaN